# Generated by Django 3.2.5 on 2021-07-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20210710_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', verbose_name='Card Number')),
            ],
        ),
    ]
