# Generated by Django 3.2.5 on 2021-07-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210710_1431'),
        ('users', '0002_rename_user_accountuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountUser',
            new_name='User',
        ),
    ]
