# Generated by Django 3.2.5 on 2021-07-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_owner'),
        ('users', '0004_auto_20210710_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Card Number'),
        ),
    ]
