# Generated by Django 3.2.5 on 2021-07-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='card_number',
            new_name='test_card_number',
        ),
    ]
