# Generated by Django 3.2.5 on 2021-07-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_card_number_user_test_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test_card_number',
            new_name='card_number',
        ),
    ]
