# Generated by Django 3.2.5 on 2021-07-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
    ]
